#!/bin/bash

private_ip=$(ifconfig | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}')
config_file_shadowsocks="Shadowsocks.json"
if [ -e $config_file_shadowsocks ]; then
	echo "file" + $config_file_shadowsocks + " already exists!"
else
	#Text naar het textbestand schrijven | Hier de verschillende gegevens inzetten als die nodig zijn(poorten en wachtwoorden)
	echo '{' >> $config_file_shadowsocks
	echo '     "server":"'$private_ip'",' >> $config_file_shadowsocks
	echo '     "port_password": {' >> $config_file_shadowsocks
	echo '        "8381": "password1",' >> $config_file_shadowsocks
	echo '        "8382": "password2",' >> $config_file_shadowsocks
	echo '        "8383": "password3",' >> $config_file_shadowsocks
	echo '        "8384": "password4",' >> $config_file_shadowsocks
	echo '        "8385": "password5",' >> $config_file_shadowsocks
	echo '        "8386": "password6",' >> $config_file_shadowsocks
	echo '    },' >> $config_file_shadowsocks
	echo '     "local_port":1080,' >> $config_file_shadowsocks
	echo '     "password":"Password123",' >> $config_file_shadowsocks
	echo '     "timeout":600,' >> $config_file_shadowsocks #Dit is 10 minuten geen reactie dan zet hij de verbinding uit
	echo '     "method":"chacha20"' >> $config_file_shadowsocks
	echo '}' >> $config_file_shadowsocks
fi
